# <span style='color:blue'> LAB2: </span>
# <span style='color:blue'> PYTORCH INTRODUCTION </span>

# <span style='color:red'> Part 1: Python as Deep Learning Platform -----------------------------------------------------</span>

### 1.1 - Verify PyTorch Installation

In [1]:
# Import necessary packages

import numpy as np
import torch

In [44]:
# Define a random torch tensor of shape (5, 3)

x = torch.rand(5, 3)
print(x)

tensor([[0.2389, 0.3478, 0.9061],
        [0.5431, 0.8342, 0.1228],
        [0.2831, 0.8943, 0.9670],
        [0.6180, 0.6064, 0.7045],
        [0.7800, 0.1388, 0.7114]])


In [3]:
# This lines ensures PyTorch can communicate with your GPU for hardware acceleration

torch.cuda.is_available()

False

# <span style='color:red'> Part 2: Neural Network Workflow in PyTorch (Simple Linear Regression) ----------</span>

### 2.1 - Prepare Data

In [4]:
%matplotlib inline

import matplotlib.pyplot as plt

In [45]:
# Generate training data for x and y

x_train = np.arange(11, dtype = np.float32)
x_train = x_train[:, np.newaxis] # [:, np.nexaxis] re-orient the x_train so that it's in vertical orientation

y_train = (2 * x_train) + 1

In [46]:
print(x_train)

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [47]:
print(y_train)

[[ 1.]
 [ 3.]
 [ 5.]
 [ 7.]
 [ 9.]
 [11.]
 [13.]
 [15.]
 [17.]
 [19.]
 [21.]]


### 2.2 - Define Model

In [48]:
# A neural network model in PyTorch is a class 

class linearRegression(torch.nn.Module):
    
    def __init__(self, input_dim, output_dim): # Initializes the model with a linear layer with input/output dimension
        
        super(linearRegression, self).__init__() # This line allows us to use attributes/methods from torch.nn.Module
        
        self.linear = torch.nn.Linear(input_dim, output_dim) # Define a single linear layer with input/output dimensions

    def forward(self, x): # This function describes the information flow within the network from input -> output
        
        out = self.linear(x) # We only have a single layer so the network output = output of the linear layer 
        
        return out

### 2.3 - Select Hyperparameters

In [49]:
# Initialize our neural network model with input and output dimensions
model = linearRegression(input_dim = 1, output_dim = 1)

# Define the learning rate and epoch (# of iterations)
learning_rate = 0.01
epochs = 100

# Define loss function and optimizer
loss_func = torch.nn.MSELoss() 
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# Run this line if you have PyTorch GPU version
if torch.cuda.is_available():
    model.cuda()

### 2.4 - Identify Tracked Values

In [50]:
# Define a list or numpy array placeholder to keep track of our training loss

train_loss_list = []

### 2.5 - Train Model

In [54]:
# Convert our dataset (inputs and targets) into torch tensors

if torch.cuda.is_available():
    inputs = torch.from_numpy(x_train).cuda() # If using GPU version, transfer the dataset to GPU memory
    targets = torch.from_numpy(y_train).cuda()
else:
    inputs = torch.from_numpy(x_train)
    targets = torch.from_numpy(y_train)

# TRAINING LOOP-------------------------------------------------------------------------

for epoch in range(epochs): # For each epoch (i.e. single pass on the training dataset)

    optimizer.zero_grad() # Empty the gradient buffer so each learning event per epoch is separate

    outputs = model(inputs) # Forward pass the inputs through the network to produce outputs 

    loss = loss_func(outputs, targets) # Compute the loss via comparing the output with expected targets
    
    train_loss_list.append(loss.item()) # Save the loss value to train_loss_list we defined
    
    loss.backward() # Compute how much changes to be made to weights/biases

    optimizer.step() # Update the weights/biases according to learning rate

    print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 4.8661375330993906e-05
epoch 1, loss 4.812289625988342e-05
epoch 2, loss 4.758340946864337e-05
epoch 3, loss 4.7050139983184636e-05
epoch 4, loss 4.652554707718082e-05
epoch 5, loss 4.6008804929442704e-05
epoch 6, loss 4.549218647298403e-05
epoch 7, loss 4.4984117266722023e-05
epoch 8, loss 4.448205800144933e-05
epoch 9, loss 4.398417877382599e-05
epoch 10, loss 4.34951507486403e-05
epoch 11, loss 4.3007577914977446e-05
epoch 12, loss 4.252995495335199e-05
epoch 13, loss 4.205289587844163e-05
epoch 14, loss 4.158197407377884e-05
epoch 15, loss 4.1120045352727175e-05
epoch 16, loss 4.066004476044327e-05
epoch 17, loss 4.0206348785432056e-05
epoch 18, loss 3.975789513788186e-05
epoch 19, loss 3.931233732146211e-05
epoch 20, loss 3.8874102756381035e-05
epoch 21, loss 3.844023376586847e-05
epoch 22, loss 3.8009780837455764e-05
epoch 23, loss 3.758515958907083e-05
epoch 24, loss 3.716699211508967e-05
epoch 25, loss 3.675042535178363e-05
epoch 26, loss 3.634091262938455e-05
epo

### 2.6 - Visualization and Evaluation

In [55]:
with torch.no_grad(): # Telling PyTorch we aren't passing inputs to the model for training purpose, which requires gradient
    
    if torch.cuda.is_available(): # If you are using GPU version
        
        # 1. Convert x_train (np.array) -> torch tensors with torch.from_numpy()
        # 2. Transfer x_train to GPU using .cuda()
        # 3. Feed forward x_train to model to obtain the output using model()
        # 4. Since the model lives in GPU, we should bring back the model output to CPU with .cpu()
        # 5. Finally convert the torch tensor to numpy with .numpy()
        predicted = model(torch.from_numpy(x_train).cuda()).cpu().numpy() 
        
    else:
        
        # With CPU version, steps 2,3,4 above is not needed
        predicted = model(torch.from_numpy(x_train)).numpy()
    
    # Print the predicted outputs - i.e., y-values and weight and biases in the trained neural network
    print(predicted) 
    print("a: " + str(model.linear.weight.cpu().numpy()), "b: " + str(model.linear.bias.cpu().numpy()))

[[ 1.0074425]
 [ 3.0063705]
 [ 5.0052986]
 [ 7.004227 ]
 [ 9.003155 ]
 [11.002084 ]
 [13.001012 ]
 [14.99994  ]
 [16.998867 ]
 [18.997797 ]
 [20.996725 ]]
a: [[1.9989282]] b: [1.0074425]


In [ ]:
# Plot the predicted-y (blue line) vs expected targets (black dots)

plt.figure(figsize = (10, 7))

plt.plot(predicted, '--', linewidth = 3)
plt.plot(x_train, y_train, 'o', color = 'black', markersize = 10)
plt.xlabel('x', fontsize = 50)
plt.ylabel('y', fontsize = 50)

# <span style='color:red'> Part 3: Python Concepts for PyTorch ---------------------------------------------------------</span>

### 3.1 - Python Classes

In [ ]:
class Pokemon():
    def __init__(self, Name, Type, Health): # Define attributes for the Pokemon object
        self.Name = Name
        self.Type = Type 
        self.Health = Health
        
    # Define methods for the Pokemon object
    
    def whats_your_name(self): # Your method can directly use the attributes defined in __init__
        print("My name is " + self.Name + "!")

    def attack(self):
        print("Electric attack! Zap!!")

    def dodge(self):
        print("Pikachu Dodge!")

    def evolve(self):
        print("Evolving to Raichu!!")

In [ ]:
pk1 = Pokemon(Name = "Pikachu", Type = "Electric", Health = 70)

In [ ]:
pk1.Name

In [ ]:
pk1.whats_your_name()

In [ ]:
pk1.attack()

### 3.2 - PyTorch Tensors vs Numpy Arrays

In [ ]:
# Defining a numpy array
array1 = np.array([1,2,3,4]) 
print(array1, type(array1))

In [ ]:
# Defining a torch tensor
tensor1 = torch.tensor([1,2,3,4])
print(tensor1, type(tensor1))

In [ ]:
# Converting numpy array to torch tensor
array1_torch = torch.from_numpy(array1)
print(array1_torch, type(array1_torch))

In [ ]:
# Converting torch tensor to numpy array
tensor1_numpy = tensor1.numpy()
print(tensor1_numpy, type(tensor1_numpy))

### 3.3 - Handling Torch Tensors

In [ ]:
# Transferring your torch tensor to CPU
tensor1_cpu = tensor1.cpu()
print(tensor1_cpu.device)

In [ ]:
# Transferring your torch tensor to GPU
tensor1_gpu = tensor1.cuda()
print(tensor1_gpu.device)